version: 2.1

orbs:
  slack: circleci/slack@4.10.1
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-ecs: circleci/aws-ecs@2.2.1
  terraform: circleci/terraform@3.1.0

commands:
  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
jobs:
  build-and-push-image:
    working_directory: ~/fastapi-ecs-fargate
    docker:
        - image: cimg/python:3.10.4
    steps:
      - setup_remote_docker:
          version: 20.10.12
      - aws-ecr/build-and-push-image:
          create-repo: true
          repo: $AWS_RESOURCE_NAME_PREFIX-registry
          tag: latest,$CIRCLE_SHA1
          region: us-east-1

workflows:
  build-and-deploy:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          filters:
            branches:
              only: [ main ]
      - terraform/validate:
          checkout: true
          context: terraform
          filters:
            branches:
              only: [ main ]
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          filters:
            branches:
              only: [ main ]
          requires:
            - terraform/validate
      - hold-tf-apply:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: [ main ]
          requires:
            - hold-tf-apply
      - build-and-push-image:
          context:
            - fastapi-ecs-fargate-context
          filters:
            branches:
              only: [ main ]
          requires:
            - terraform/apply
      - aws-ecs/deploy-service-update:
          cluster-name: $AWS_RESOURCE_NAME_PREFIX-cluster
          container-image-name-updates: container=$AWS_RESOURCE_NAME_PREFIX-service,tag=${CIRCLE_SHA1}
          family: $AWS_RESOURCE_NAME_PREFIX-service
          context:
            - fastapi-ecs-fargate-context
          filters:
            branches:
              only: [ main ]
          requires:
            - build-and-push-image
